Repository alesan99/mari0_ae, pull requests merged in 2021-10, with the labels that each got.

#225 "player(not)near" cleanup and "enemy(not)near" added
  enemy.lua
Labels: enhancement, custom enemies

#223 shell enemies killing enemies after being stomped and waking up
  enemy.lua
Labels: bug

#159 Text Highlighting
  gui.lua
Labels: enhancement

#208 Fix watergravity
  enemy.lua
Labels: bug

#169 added "dontPlaySoundsOffscreen"
  enemy.lua
Labels: enhancement, custom enemies

#195 Added "facesPlayerY"
  enemy.lua
Labels: enhancement, custom enemies
