Repository alesan99/mari0_ae, pull requests merged in 2022-12, with the labels that each got.

#450 Added "reflectsFireballs"
  enemy.lua
  fireball.lua
Labels: custom enemies

#442 Animation Folders
  animationsystem.lua
Labels: enhancement

#445 Enter pipes while not jumping
  mario.lua
Labels: bug

#443 Added region trigger ranges to Hitboxdebug
  game.lua
Labels: enhancement

#433 Added "if coins/points/collectables" animation conditions
  animation.lua
  animationguiline.lua
Labels: enhancement

#435 HUD fixes
  game.lua
Labels: bug, change

#431 Raccoon tail now triggers switch blocks and pows
  mariotail.lua
Labels: bug

#427 Added exit confirmations
  editor.lua
  main.lua
Labels: new feature

#466 Enemy Rightclick Fixes
  editor.lua
Labels: bug

#419 Fix clamptolevelwidth/height background property
  game.lua
Labels: bug
