Repository alesan99/mari0_ae, pull requests merged in 2022-03, with the labels that each got.

#351 Fence Changes
  mario.lua
Labels: bug

#334 Added custom enemy offsets (With "offsetable" property)
  editor.lua
  game.lua
Labels: enhancement, custom enemies

#347 Low time music-related changes
  animation.lua
  editor.lua
  game.lua
  languages/english.json
Labels: new feature, enhancement

#283 Custom Enemy better right clicks
  editor.lua
  enemy.lua
  main.lua
Labels: new feature, custom enemies

#322 Added string concatenation to custom timer
  enemy.lua
Labels: enhancement, custom enemies

#177 Added "print" custom timer action
  enemy.lua
Labels: enhancement, custom enemies

#134 Added "flickerTime" (enemy property)
  enemy.lua
Labels: enhancement, custom enemies

#184 Added "waitforinput" and "waitfortrigger"
  animation.lua
  animationguiline.lua
Labels: enhancement

#356 Fix for "rightclick"
  enemy.lua
Labels: bug

#369 Waitfortrigger fix
  animation.lua
  animationtrigger.lua
  enemy.lua
Labels: bug
