Repository alesan99/mari0_ae, pull requests merged in 2023-01, with the labels that each got.

#473 Fixed turret knockback in older versions
  enemies/turret.lua
Labels: bug

#476 Persistent editor tools
  editor.lua
  main.lua
Labels: enhancement

#470 Fix Mario becoming invisible on "stopplayeranimation"
  mario.lua
Labels: bug

#469 Fixed Grate slabs
  game.lua
Labels: bug

#467 Fix if logic
  enemy.lua
Labels: bug, custom enemies

#424 Fixed animations being overridden
  editor.lua
Labels: bug

#478 Refactoring Persistent tools
  editor.lua
Labels: bug

#417 Fix custommusiciinput always being active
  editor.lua
Labels: bug

#416 Adjust scaling with earthquake
  enemies/glados.lua
  game.lua
Labels: bug, accuracy

#415 Fixed Rocket Turret Despawning
  enemies/rocketturret.lua
Labels: bug

#414 Fixed mario being pushed through some entities with wind
  variables.lua
Labels: bug

#412 Offset spawn now shows on menu
  menu.lua
Labels: bug

#405 Improve links and selections
  editor.lua
Labels: bug, enhancement

#452 Make Hitting Things From Below Blocks Not Suck
  mario.lua
Labels: change, enhancement, custom enemies

#400 Trailing comma support in arrays
  JSON.lua
Labels: enhancement

#471 Switch slider to input on timer
  entity.lua
Labels: change

#430 Added input to timelimit changer
  editor.lua
  gui.lua
Labels: change, enhancement

#423 Added "Set available portals" animation action
  animation.lua
  animationguiline.lua
Labels: enhancement

#406 Change link tool
  editor.lua
Labels: change, enhancement

#422 Added stopsound custom timer action and "stopSoundOnDeath" enemy property
  enemy.lua
Labels: enhancement, custom enemies

#421 Change Hud and Ending Color picker to Dropdown.
  editor.lua
  entity.lua
  gui.lua
  main.lua
  variables.lua
Labels: change, enhancement

#472 Increase camera stop region
  entity.lua
Labels: change

#398 Menu Adjustments
  menu.lua
Labels: change, enhancement

#487 Adds "Requires Players" Animation Condition
  animation.lua
  animationguiline.lua
Labels: enhancement

#489 HITBOXDEBUG Improvments
  game.lua
  main.lua
Labels: enhancement

#490 Adds "platformchecktable" and "trackplatformchecktable"
  track.lua
Labels: enhancement, custom enemies

#488 Adds "Make invincible" Animation Trigger
  animation.lua
  animationguiline.lua
Labels: enhancement

#492 Adds "Change Switch State" Animation Trigger
  animation.lua
  animationguiline.lua
  blocktogglebutton.lua
  flipblock.lua
  game.lua
Labels: enhancement

#496 Fixed seesaw platforms not being semisolid in mario maker phsysics
  seesawplatform.lua
Labels: bug

#495 Fix grouping bug with coins
  mario.lua
Labels: bug

#494 Fix Boo Stretch colliding with fireballs when hidden
  enemies/drybones.lua
Labels: bug

#497 Fixed Boo checking if it's not a spiny egg
  enemies/boo.lua
Labels: bug

#493 Added missing supersize properties to half enemies
  entity.lua
Labels: change

#498 Fixed inefficient enemybase load code
  enemies.lua
Labels: change
