Repository alesan99/mari0_ae, pull requests merged in 2024-08, with the labels that each got.

#589 LÖVE 11 fixes
  .android-resources/drawable-hdpi/love.png
  .android-resources/drawable-mdpi/love.png
  .android-resources/drawable-xhdpi/love.png
  .android-resources/drawable-xxhdpi/love.png
  .android-resources/drawable-xxxhdpi/love.png
  .github/workflows/compile.yaml
  animation.lua
  dialogbox.lua
  enemies.lua
  flipblock.lua
  frozencoin.lua
  game.lua
  ice.lua
  main.lua
  mappack.lua
  mario.lua
  physics.lua
  powblock.lua
  quad.lua
  smbsitem.lua
  spriteloader.lua
  utils.lua
Labels: new feature

#574 Fix platforms again
  physics.lua
Labels: bug

#625 Fix AppImage builds
  .github/workflows/compile.yaml
Labels: bug

#629 Cleanup file opening
  editor.lua
  filebrowser.lua
  menu.lua
Labels: change

#615 Fixed Certain Colors not Working
  alesans_entities/characters/mario/config.json
  alesans_entities/characters/toad/config.json
  characters.lua
  game.lua
  graphics/entitytooltips/iceflower.png
  main.lua
  mario.lua
  menu.lua
  variables.lua
Labels: bug, change

#403 Better Hammer Bros
  enemies/hammerbro.lua
  enemies/upfire.lua
  mario.lua
  variables.lua
Labels: uncertain, change

#614 Removed `"only_for_alesans_entities"`
  alesans_entities/mappacks/alesans_entities_mappack/text.txt
  levelscreen.lua
  mappacks/alesans_entities_mappack/text.txt
  menu.lua
Labels: change

#646 Fix if operators (for real this time)
  enemy.lua
Labels: bug

#645 Add per-mappack suspend/save support with the option for map creators to save progress automatically
  animation.lua
  animationguiline.lua
  game.lua
  languages/english.json
  main.lua
  mappack.lua
  menu.lua
  variables.lua
Labels: change, new feature, enhancement
